#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
export CYBER_VENV=/home/daherr/Code/git/virt_sascyber/bin/activate
export CYBER_JOBEXEC=DIP
export CYBER_TASK=123
export CYBER_STATUS_FILE_DIRECTORY=/tmp
export CYBER_ARGS=/home/daherr/Code/git/Analysis.AnalyticsConfig/test/nf.dstips.IntDstIps.json
export CYBER_ROOT=/home/daherr/tmp/sascyber
export CYBER_DEV_STATUS=DEBUG
export CYBER_DEFAULT_LOGGING=true
export CYBER_LOG=/home/daherr/Code/git/Analysis.AnalyticsConfig/log/logformat.json
export CAS_CLIENT_SSL_CA_LIST=$HOME/cascert.pem

alias sas9="/home/sas/SASHome/SASFoundation/9.4/sas"
alias la="ls -lah"
alias ipy="ipython --pprint --no-simple-prompt"
alias jpnb="jupyter notebook"
alias py="python3.6"
alias pinstall="pip3.6 install"
alias vsascy="source /home/daherr/Code/virtual_envs/virt_sascyber/bin/activate"
alias mux="tmuxinator"

# binding keys
bindkey -v # move to vi-mode
bindkey -M viins 'jk' vi-cmd-mode
bindkey '^R' history-incremental-search-backward

# prompt information for powerlevel9k (was somehow wiped)
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vi_mode root_indicator background_jobs history time)
